<a href="https://colab.research.google.com/github/NicolasB7/PID/blob/main/prevenci_n_inteligente_del_dengue_pid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**CONECTARSE A DRIVE.**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

**SE IMPORTAN LAS BASE DE DATOS Y SE CREA UN DATARFRAME.**

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter

d2020 = 'drive/Shareddrives/PID/Dengue/dengue_abierto2020.csv'
d2021 = 'drive/Shareddrives/PID/Dengue/dengue_abierto2021.csv'
d2022 = 'drive/Shareddrives/PID/Dengue/dengue_abierto2022.csv'
d2023 = 'drive/Shareddrives/PID/Dengue/dengue_abierto2023.csv'
datosHistoricos = pd.concat(map(pd.read_csv, [d2020, d2021, d2022, d2023]), ignore_index=True)
datosHistoricos

,FECHA_ACTUALIZACION,ID_REGISTRO,SEXO,EDAD_ANOS,ENTIDAD_RES,MUNICIPIO_RES,HABLA_LENGUA_INDIG,INDIGENA,ENTIDAD_UM_NOTIF,MUNICIPIO_UM_NOTIF,...,INMUNOSUPR,CIRROSIS_HEPATICA,EMBARAZO,DEFUNCION,DICTAMEN,TOMA_MUESTRA,RESULTADO_PCR,ESTATUS_CASO,ENTIDAD_ASIG,MUNICIPIO_ASIG
0,2020-12-30,404569,2,63,28,33,2,1,28,33,...,2,2,2,2,5.0,1,5,2,28,33
1,2020-12-30,760644,1,42,18,8,2,2,18,17,...,2,2,2,2,5.0,2,5,1,18,8
2,2020-12-30,760647,2,16,31,96,2,2,31,96,...,2,2,2,2,5.0,2,5,1,31,96
3,2020-12-30,760654,1,76,12,1,2,2,12,1,...,2,2,2,2,5.0,1,5,3,12,1
4,2020-12-30,760657,1,20,30,142,2,2,30,116,...,2,2,2,2,5.0,1,5,2,30,142
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217952,2023-02-13,1005253,1,45,23,5,2,2,23,5,...,2,2,2,2,5.0,1,5,3,23,5
217953,2023-02-13,1005240,2,32,23,5,2,2,23,5,...,2,2,2,2,5.0,2,5,1,23,5
217954,2023-02-13,1005269,2,0,16,52,2,2,16,52,...,2,2,2,2,5.0,2,5,1,16,52
217955,2023-02-13,1005272,1,65,31,96,2,2,31,96,...,2,2,2,2,5.0,1,5,3,23,5
217956,2023-02-13,1005282,1,15,6,7,2,2,6,7,...,2,2,2,2,5.0,1,2,2,6,7

**DESCRIPTOR DE TERMINOS.**

In [ ]:
pd.read_excel('drive/Shareddrives/PID/Dengue/Descriptores_Dengue.xlsx') # Descriptor de terminos.

,NO.,NOMBRE DE VARIABLE,DESCRIPCION,FORMATO O FUENTE
0,1,FECHA_ACTUALIZACION,LA BASE DE DATOS SE ACTUALIZA SEMANALMENTE. ES...,"AAAA-MM-DD, 9999-99-99: CUANDO NO HAY REGISTRO"
1,2,ID_REGISTRO,NÚMERO DE INDETIFICADOR DEL CASO,TEXTO
2,3,SEXO,IDENTIFICA EL SEXO DEL PACIENTE,CATÁLOGO: SEXO
3,4,EDAD_ANOS,IDENTIFICA LA EDAD EN AÑOS DEL PACIENTE,NÚMERICA EN AÑOS
4,5,ENTIDAD_RES,IDENTIFICA LA ENTIDAD DE RESIDENCIA DEL PACIENTE,CATÁLOGO: ENTIDADES
5,6,MUNICIPIO_RES,IDENTIFICA EL MUNICIPIO DE RESIDENCIA DEL PACI...,CATÁLOGO: MUNICIPIOS
6,7,HABLA_LENGUA_INDIG,IDENTIFICA SI EL PACIENTE HABLA LENGUA INDIGENA,CATÁLOGO: SI /NO
7,8,INDIGENA,IDENTIFICA SI EL PACIENTE SE AUTOIDENTIFICA CO...,CATÁLOGO: SI /NO
8,9,ENTIDAD_UM_NOTIF,IDENTIFICA LA ENTIDAD DONDE SE ENCUENTRA LA UN...,CATÁLOGO: ENTIDADES
9,10,MUNICIPIO_UM_NOTIF,IDENTIFICA EL MUNICIPIO DONDE SE ENCUENTRA LA ...,CATÁLOGO: MUNICIPIOS
10,11,INSTITUCION_UM_NOTIF,IDENTIFICA LA INSTITUCIÓN DE LA UNIDAD MEDICA ...,CATÁLOGO: INSTITUCIÓN
11,12,FECHA_SIGN_SINTOMAS,IDENTIFICA LA FECHA DE INICIO DE SIGNOS Y SINT...,"AAAA-MM-DD, 9999-99-99: CUANDO NO HAY REGISTRO"
12,13,TIPO_PACIENTE,IDENTIFICA EL TIPO DE ATENCIÓN QUE RECIBIÓ EL ...,CATÁLOGO: TIPO_PACIENTE
13,14,HEMORRAGICOS,PRESENCIA DE TRASTORNOS HEMORRÁGICOS,CATÁLOGO: SI /NO
14,15,DIABETES,PRESENCIA DE DIABETES,CATÁLOGO: SI /NO
15,16,HIPERTENSION,PRESENCIA DE HIPERTENSIÓN,CATÁLOGO: SI /NO
16,17,ENFERMEDAD ULC_PEPTICA,PRESENCIA DE ENFERMEDAD ULCERO PÉPTICA,CATÁLOGO: SI /NO
17,18,ENFERMEDAD_RENAL,PRESENCIA DE ENFERMEDAD RENAL,CATÁLOGO: SI /NO
18,19,INMUNOSUPR,PRESENCIA DE INMUNOSUPRESIÓN,CATÁLOGO: SI /NO
19,20,CIRROSIS_HEPATICA,PRESENCIA DE CIRROSIS HEPÁTICA,CATÁLOGO: SI /NO
20,21,EMBARAZO,IDENTIFICA SI LA PACIENTE ESTÁ EMBARAZADA,CATÁLOGO: SI /NO
21,22,DEFUNCION,INDICA SI EL PACIENTE FALLECIÓ,CATÁLOGO: SI /NO
22,23,DICTAMEN,IDENTIFICA EL RESULTADO DE LA DICTAMINACIÓN PA...,CATÁLOGO: DICTAMEN
23,24,TOMA_MUESTRA,IDENTIFICA SI AL PACIENTE SE LE TOMÓ MUESTRA,CATÁLOGO: SI /NO
24,25,RESULTADO PCR,IDENTIFICA EL RESULTADO DE LA PRUEBA PCR REALI...,CATÁLOGO: RESULTADO_PCR
25,26,ESTATUS_CASO,ESTATUS DEL CASO,CATÁLOGO: ESTATUS_CASO
26,27,ENTIDAD_ASIG,IDENTIFICA LA ENTIDAD A LA QUE SE ASIGNÓ EL CASO,CATÁLOGO: ENTIDADES
27,28,MUNICIPIO_ASIG,IDENTIFICA EL MUNICIPIO AL QUE SE ASIGNÓ EL CASO,CATÁLOGO: MUNICIPIOS

**HOJAS DEL CATALOGO.**

In [ ]:
hojas = pd.read_excel('drive/Shareddrives/PID/Dengue/Catálogos_Dengue.xlsx', sheet_name=None) # Hojas del catalogo
catalogo = []
catalogo = list(hojas.keys())
print(catalogo)

['CATÁLOGO ESTATUS_CASO', 'CATALOGO RESULTADO_PCR ', 'CATÁLOGO DICTAMEN', 'CATÁLOGO INSTITUCION', 'CATÁLOGO TIPO_PACIENTE', 'CATÁLOGO MUNICIPIO', 'CATÁLOGO ENTIDAD', 'CATALOGO SI_NO', 'CATÁLOGO SEXO']

**SE BUSCA A JALISCO EN EL CATALOGO ENTIDAD.**

In [ ]:
entidades = pd.read_excel('drive/Shareddrives/PID/Dengue/Catálogos_Dengue.xlsx', sheet_name='CATÁLOGO ENTIDAD') # SE BUSCA A JALISCO EN EL CATALOGO ENTIDAD
jalisco = entidades[entidades.ENTIDAD_FEDERATIVA.eq('JALISCO')]
jalisco

    CLAVE_ENTIDAD ENTIDAD_FEDERATIVA ABREVIATURA
13             14            JALISCO          JC

**CASOS CONFIRMADOS EN JALISCO.**

In [ ]:
casosEnJalisco = datosHistoricos[datosHistoricos.ENTIDAD_UM_NOTIF.eq(14)] # Casos confirmados en Jalisco
casosEnJalisco

,FECHA_ACTUALIZACION,ID_REGISTRO,SEXO,EDAD_ANOS,ENTIDAD_RES,MUNICIPIO_RES,HABLA_LENGUA_INDIG,INDIGENA,ENTIDAD_UM_NOTIF,MUNICIPIO_UM_NOTIF,...,INMUNOSUPR,CIRROSIS_HEPATICA,EMBARAZO,DEFUNCION,DICTAMEN,TOMA_MUESTRA,RESULTADO_PCR,ESTATUS_CASO,ENTIDAD_ASIG,MUNICIPIO_ASIG
13,2020-12-30,760702,2,46,14,39,2,2,14,39,...,2,2,2,2,5.0,2,5,1,14,39
17,2020-12-30,760721,2,45,14,67,2,2,14,67,...,2,2,2,2,5.0,2,5,1,14,67
20,2020-12-30,760737,2,32,14,98,2,2,14,39,...,2,2,2,2,5.0,2,5,1,14,98
29,2020-12-30,760773,1,22,14,39,2,2,14,39,...,2,2,2,2,5.0,1,5,3,14,39
94,2020-12-30,760241,2,12,18,20,2,2,14,67,...,2,2,2,2,5.0,1,2,2,18,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217861,2023-02-13,1001538,1,27,14,39,2,2,14,98,...,2,2,2,2,5.0,1,5,3,14,39
217891,2023-02-13,1006217,2,0,14,98,2,2,14,39,...,2,2,2,2,5.0,2,5,1,14,98
217898,2023-02-13,1006300,1,19,14,63,2,2,14,39,...,2,2,1,2,5.0,1,5,1,14,63
217907,2023-02-13,1006316,1,91,14,120,2,2,14,120,...,2,2,2,2,5.0,1,5,3,14,120
217922,2023-02-13,1006493,2,15,14,120,2,2,14,120,...,2,2,2,2,5.0,1,5,1,14,120

**SE BUSCA LA CLAVE DE CASOS CONFIRMADOS.**

In [ ]:
pd.read_excel('drive/Shareddrives/PID/Dengue/Catálogos_Dengue.xlsx', sheet_name=catalogo[0]) # Se busca la clave de casos confirmados

   CLAVE DESCRIPCIÓN
0      1    PROBABLE
1      2  CONFIRMADO
2      3  DESCARTADO

**CASOS CONFIRMADOS EN JALISCO.**

In [ ]:
casosEnJaliscoConfirmados = casosEnJalisco[casosEnJalisco.ESTATUS_CASO.eq(2)] # Casos confirmados
casosEnJaliscoConfirmados

,FECHA_ACTUALIZACION,ID_REGISTRO,SEXO,EDAD_ANOS,ENTIDAD_RES,MUNICIPIO_RES,HABLA_LENGUA_INDIG,INDIGENA,ENTIDAD_UM_NOTIF,MUNICIPIO_UM_NOTIF,...,INMUNOSUPR,CIRROSIS_HEPATICA,EMBARAZO,DEFUNCION,DICTAMEN,TOMA_MUESTRA,RESULTADO_PCR,ESTATUS_CASO,ENTIDAD_ASIG,MUNICIPIO_ASIG
94,2020-12-30,760241,2,12,18,20,2,2,14,67,...,2,2,2,2,5.0,1,2,2,18,20
105,2020-12-30,760360,2,44,14,39,2,2,14,39,...,2,2,2,2,5.0,1,2,2,14,39
335,2020-12-30,760381,1,18,14,120,2,2,14,39,...,2,2,2,2,5.0,1,2,2,14,120
371,2020-12-30,761374,2,33,14,70,2,2,14,39,...,2,2,2,2,5.0,1,5,2,18,20
390,2020-12-30,761451,1,20,14,100,2,2,14,67,...,2,2,1,2,5.0,1,2,2,14,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214154,2023-02-13,1007009,2,10,14,22,2,2,14,22,...,2,2,2,2,5.0,1,2,2,14,22
215101,2023-02-13,1002231,1,55,14,5,2,2,14,39,...,2,2,2,2,5.0,1,5,2,14,5
216717,2023-02-13,1003197,2,33,14,100,2,2,14,67,...,2,2,2,2,5.0,1,2,2,14,100
216764,2023-02-13,1003019,1,25,14,99,1,1,14,99,...,2,2,2,2,5.0,1,4,2,7,31
217044,2023-02-13,1004815,2,30,6,7,2,2,14,22,...,2,2,2,2,5.0,1,2,2,6,7

**MUNICIPIOS DE JALISCO.**

In [ ]:
municipios = pd.read_excel('drive/Shareddrives/PID/Dengue/Catálogos_Dengue.xlsx', sheet_name=catalogo[5]) # Se busca los municipios del estado de Jalisco
municipios[municipios.CLAVE_ENTIDAD.eq('14')]

     CLAVE_MUNICIPIO                MUNICIPIO CLAVE_ENTIDAD
549                1                   ACATIC            14
550                2        ACATLÁN DE JUÁREZ            14
551                3     AHUALULCO DE MERCADO            14
552                4                 AMACUECA            14
553                5                 AMATITÁN            14
..               ...                      ...           ...
670              122    ZAPOTITLÁN DE VADILLO            14
671              123         ZAPOTLÁN DEL REY            14
672              124              ZAPOTLANEJO            14
673              125  SAN IGNACIO CERRO GORDO            14
674              999          NO ESPECIFICADO            14

[126 rows x 3 columns]

**CONTAGIOS CONFIRMADOS EN EL MUNICIPIO DE ZAPOPAN.**

In [ ]:
casosEnJaliscoConfirmados[casosEnJaliscoConfirmados.MUNICIPIO_UM_NOTIF.eq(120)] #Contagios en el municipio de Zapopan

,FECHA_ACTUALIZACION,ID_REGISTRO,SEXO,EDAD_ANOS,ENTIDAD_RES,MUNICIPIO_RES,HABLA_LENGUA_INDIG,INDIGENA,ENTIDAD_UM_NOTIF,MUNICIPIO_UM_NOTIF,...,INMUNOSUPR,CIRROSIS_HEPATICA,EMBARAZO,DEFUNCION,DICTAMEN,TOMA_MUESTRA,RESULTADO_PCR,ESTATUS_CASO,ENTIDAD_ASIG,MUNICIPIO_ASIG
1616,2020-12-30,762625,1,46,14,98,2,2,14,120,...,2,2,2,2,5.0,1,5,2,14,98
2424,2020-12-30,764481,1,13,14,120,2,2,14,120,...,2,2,2,2,5.0,1,5,2,14,120
4080,2020-12-30,763793,1,8,14,94,2,2,14,120,...,2,2,2,2,5.0,1,5,2,14,94
4552,2020-12-30,767210,1,15,14,120,2,2,14,120,...,2,2,2,2,5.0,1,5,2,14,120
4773,2020-12-30,765928,1,57,14,39,2,2,14,120,...,2,2,2,2,5.0,1,5,2,14,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203621,2022-12-12,978263,1,53,14,120,2,2,14,120,...,2,2,2,2,5.0,1,5,2,14,120
205974,2022-12-12,954149,1,16,14,120,2,2,14,120,...,2,2,2,2,5.0,1,2,2,14,120
208915,2022-12-12,940778,1,24,14,120,2,2,14,120,...,2,2,1,2,5.0,1,5,2,14,120
209899,2022-12-12,943215,1,23,14,120,2,2,14,120,...,2,2,2,2,5.0,1,1,2,14,120
213643,2023-02-13,1002271,1,7,14,98,2,2,14,120,...,2,2,2,2,5.0,1,5,2,6,7